<?php

return [
    // Core Actions
    'edit' => 'solar:pen-2-broken',
    'delete' => 'solar:trash-bin-trash-broken',
    'delete_permanent' => 'solar:trash-bin-minimalistic-2-broken',
    'save' => 'solar:diskette-bold-duotone',
    'plus' => 'solar:add-circle-bold',
    'restore' => 'solar:archive-up-broken',
    'archive' => 'solar:archive-down-broken',
    'refresh' => 'solar:refresh-bold',
    'success' => 'solar:check-circle-bold-duotone',
    'error' => 'solar:danger-bold-duotone',
    'info' => 'solar:info-circle-bold-duotone',
    'copy' => 'solar:copy-linear',

    // Objects
    'user' => 'solar:user-circle-bold',
    'users' => 'solar:users-group-two-rounded-bold-duotone',
    'default_icon' => 'solar:document-text-bold-duotone',
    'folder' => 'solar:folder-with-files-bold-duotone',
    'database' => 'solar:database-bold-duotone',
    'layers' => 'solar:layers-minimalistic-bold',
    'notebook' => 'solar:notebook-bold-duotone',
    'shop' => 'solar:shop-2-bold',
    'cart' => 'solar:cart-bold-duotone',
    'bill' => 'solar:bill-linear',
    'delivery' => 'solar:delivery-bold',
    'deliveryType' => 'solar:box-bold-duotone',
    'paymentMethod' => 'solar:card-2-bold-duotone',
    'disk' => 'solar:ssd-round-bold-duotone',
    'api_doc' => 'solar:black-hole-outline',
    'image' => 'solar:gallery-bold-duotone',
    'video_play' => 'solar:video-frame-play-horizontal-bold-duotone',
    'camera' => 'solar:camera-bold-duotone',

    // Communication & UI
    'letter' => 'solar:letter-bold-duotone',
    'letter_opened' => 'solar:letter-opened-bold-duotone',
    'email' => 'solar:letter-bold-duotone',
    'phone' => 'solar:outgoing-call-rounded-bold-duotone',
    'map_point' => 'solar:point-on-map-bold-duotone',
    'global' => 'solar:global-bold',
    'notifications' => 'solar:bell-bing-bold-duotone',
    'messages' => 'solar:chat-line-bold-duotone',
    'search' => 'solar:magnifer-linear',
    'search_alt' => 'solar:magnifer-zoom-in-bold-duotone',

    // Security
    'lock' => 'solar:lock-key-bold-duotone',
    'shield' => 'solar:shield-check-bold-duotone',
    'shield_warning' => 'solar:shield-warning-bold',
    'check_verified' => 'solar:check-read-bold',
    'block' => 'solar:forbidden-bold-duotone',

    // Navigation & UI Elements
    'menu' => 'solar:hamburger-menu-linear',
    'menu_toggle' => 'solar:hamburger-menu-broken',
    'parent_menu' => 'solar:clipboard-list-bold-duotone',
    'list' => 'solar:list-bold-duotone',
    'sort' => 'solar:sort-vertical-broken',
    'sort_inactive' => 'solar:sort-vertical-line-duotone',
    'arrow_up' => 'solar:alt-arrow-up-linear',
    'arrow_down' => 'solar:alt-arrow-down-linear',
    'arrow_right_double' => 'solar:double-alt-arrow-right-bold-duotone',
    'expand' => 'solar:maximize-square-minimalistic-bold-duotone',
    'fullscreen' => 'solar:full-screen-bold-duotone',

    // Tools & Dev
    'settings' => 'solar:settings-bold-duotone',
    'tools' => 'solar:wrench-bold-duotone',
    'terminal' => 'solar:terminal-bold-duotone',
    'code' => 'solar:code-bold-duotone',
    'bug' => 'solar:bug-minimalistic-bold',
    'translation' => 'solar:translation-2-linear',
    'seo' => 'solar:globus-bold-duotone',
    'attributes' => 'solar:widget-bold-duotone',
    'apps' => 'solar:widget-2-bold-duotone',
    'tuning' => 'solar:tuning-bold-duotone',
    'bookmark' => 'solar:book-bookmark-bold-duotone',
    'server' => 'solar:server-square-bold-duotone',
    'structure' => 'solar:structure-bold-duotone',
    'code_file' => 'solar:code-file-bold-duotone',
    'code_square' => 'solar:code-square-bold-duotone',
    'recycle' => 'solar:recycle-square-bold-duotone',
    'plug' => 'solar:plug-circle-bold-duotone',

    // Other
    'history' => 'solar:clock-circle-bold-duotone',
    'clock' => 'solar:clock-circle-bold-duotone',
    'star' => 'solar:star-bold-duotone',
    'box' => 'solar:box-bold-duotone',
    'link' => 'solar:link-bold-duotone',
    'logout' => 'solar:logout-bold-duotone',
    'eye' => 'solar:eye-bold-duotone',
    'eye_closed' => 'solar:eye-closed-bold',
    'bag_heart' => 'solar:bag-heart-bold-duotone',
    'heart' => 'solar:heart-bold',
    'bolt_circle' => 'solar:bolt-circle-bold-duotone',
    'api' => 'solar:api-bold-duotone',
    'test_tube' => 'solar:test-tube-minimalistic-bold-duotone',
    'chart_square' => 'solar:chart-square-bold-duotone',
    'folder_open' => 'solar:folder-open-bold-duotone',
];
